### ISSUE TITLE
Working with the resulting payload

### ISSUE THREAD

**Issue by tlianza** [bndr/gopencils#18]
Big disclaimer that I'm new to Go, but would love either a short example or a pointer to the appropriate JSON project that demonstrates how you consume/navigate the payload of the response.  The README seems pretty clear about how to auth and construct restful urls, just looking for a pointer towards the next step.  Thank you!

**Comment by bndr** [comment]
You don't really navigate the JSON, the JSON object ist loaded into your response Structure

Example: 
```
type UserExample struct {
    Id            string
    Name          string
    Origin        string
    Url           string
    SomeJsonField string
}

// Create Basic Auth
auth := gopencils.BasicAuth{"username", "password"}

// Create New Api with our auth
api := gopencils.Api("http://your-api-url.com/api/", &auth)

// Create a pointer to our response struct
resp := &UserExample{}

// Perform a GET request
// URL Requested: http://your-api-url.com/api/users/1
// The JSON data is loaded into resp variable
api.Res("users", resp).Id(1).Get()

// Now your Response Struct (resp) contains the parsed JSON, you can now access the properties.

```

**Comment by tlianza** [comment]
Ah - thanks... so if it's a more complex payload, with a header that has some meta information, then a body that might have an array of structures, one would need to create a struct that maps all of those values?  
![api_popshops_com_v3_merchants_json_account_5j442sbofhecuy31lk8gketk8](https://cloud.githubusercontent.com/assets/18635/6967934/aac56e7c-d917-11e4-939a-9c93f26fff1e.png)

**Comment by bndr** [comment]
Basically yes, you can use the json-to-go struct service e.g. http://mholt.github.io/json-to-go/ to generate the struct, then use that struct to store the response.

**Comment by tlianza** [comment]
This is perfect - thank you!
